language: node_js
install: npm install
script: npm test
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: X/J+LGohuF8mWCEfsjJnby+ke/HlyyP7vF0LvQfSnbWRph7BrhWJt5PFt95OLbylZE2i5GYDLs30T+j6l8JgktgObmaFtW9UELZ3HvcOlVCHAEvZlgyMwsXU2jCZiS6Uzm4lOVXPjfZp/TH57VYe/91bpAOzvf31sk1i0rzhqWT5+4TlayL+LZmbzaK0Fo/lphBq8hq9tfirsZjFQ+IDBDqEBJPLHKoli0Mw+u9F+NvIhhbd2XwZHjVVPwDuhc0/5xTXsiePfTAq1YFbms3acPQbSchV0nLXVEIeQcdffZk4Oqqj9HAHlQ6WXL7ag+Izw3OhVLq+Y6kLgYU1eDodsHgCORt57YAa+EhkWwWyUr5tmu6c8E1DvyEWtZc+YXP2jBsXviOd91s0dTfSQGsDUhNaqZfBP43yukXnUllMFtlqcXVJMwa63ucBB1z/4A5teLL//vqndZAWInWtUwSFnIuGzCwPguLGNRnVhUlFSJ+eTGufEdp4DnS6992JdOadAxxoSBh5D5KIzyPFQWMMg+OTp05woNPWwwJFt+o2p+TzspGKwsnDSdR0Wa3ywE/CnA+/A7zJThSj3AS/+6Lff3w/26QHYcpSpYxhqOsxWIQgC1s4MlSLmYrROZ191bV985EXgSnOrjk/ECGU54gE5Y4hAR65KriD5rH3d59fNbU=
  - secure: rqZC1T41eNZYIw44xeXjcqKxXTszB1pRbjHZvWrWjqDtK2K/9JT0L9BK/W5K7nTWPQ/PAnrhK8C8bNnDQR7wXGJClzHgp5InNWOr/OFqPsVzYkrdayFWiigUmLt2+FJh11DWTZYqC57yr46jjhCw7wmIvdZuIw4fAVYluw+v7j62uXEE/MCmvPzBvSrQ4+nfX53pDlB+AxfUwMWJe1gfdb1me32CiXDnWL1PKUphn8+Fdwb/LxhgupPvmiUnHImiDBp+3uhXTb2Xn4eq9Z48eHnhSUHJ2JLbGVRZYTPygh9MoUd7ITSp6zwnNW9TGIticviIDamp/aevGBdQxJ/V7hbQl4Ry4mGS0AmOLhz0dU50Fw5Y4JHJFgAMcH+3U5/hIIS26giYYaXzq79gNuqPxDVgle/Zdc2R7u62zGhYtaadsQtbMXCZMoKIruyn/rcw/55fDShWWGfxH8nlCBVbZst0azBPGXBoYNkbSwnhX/npcxFJqcOnTJsJcahwCdGQHLacqBRpEs3rRHgIZu4mSEjmoSyHESIF0ln7+QsQSiLEEnaOriFqEla/UcRYKs9eGyiK4jgyuTNVr4v1Uy14GILhEx5w17OuiKGYwghB/WVekIaj5Y9hRP+7sUjbHM6Us62yq6ESKQlT60deZeNkCR0OAmxTkwFc9CNr7HWYa+U=
  - secure: opTafvLCYjyyLSg76M3Vpf8+0R4OMrvao36ICtLFvmy7Y1nudHEbMpS2w+ZbGS25XK1GzhQ1HKKnWeRmmlz2LB7xkCCkCQrdjllOBkfslLYUHtbRoAZR3IjBjiDEL20sWvMJ58K189Eh58Bv+AcZRlO2gc/4FgQDeTuqu3pwDPiPxpRC02VimOS0RNihz+6k/m2CnMaWUprjYSZ/qjAWfErtSHxGEhFgjsyNat5f1TPeCOGg76vl+Tlx1ZKKMawtRekXQjnz/g8fvuCqqUl4HgEQoKQ/3mgIOR+OqYTbOIPZ13mwwma+Gpc2ijDO1pqC0Pj80RbbNXT6g3z/8HgGkojf6C11Ymt2PWuImXy2QKASOdUP4S8lImUysmL9ImERrxUUfTL8gxD+7vjLTPFzIUfErjTyFsOPHunyKGu+8vd8A9ZkosVPuiWfGRm3YT+AurZbWK3/WEkK7DzKz3QAM3q+M+2FITGaI2KI2gZ9cxPwfqhLOn3OPYOW5zUBm7ndTYqIShGU/Ql3TWdxp7T1sETekKW79qTosHtJCZR7LgsZLGX47AnxNxPBEKaXsf66JdduaIl22RPEppndehRbQDByHqQEXEyM4Ifm8aCmaHzLqWatZjKBD9EsoEaCrz6yucpVQbYcaJxhSZFLoQF6EFJTRTEOIg99mfwG3cQqjX0=
