language: node_js
install: npm install
script: npm test
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
    secure: x4BAo4+m2FdLbZNUMTPV21Bo7SKpdNM2cUK5bdfA8l1grzgzBWNyrt+btPKPQJiI6Qq1WNx8+VvOmgcyMxjaSEI9lFbMR+JTH/3oF2/agai8jN09bsgysVyAffe5kPzd3gsMXO1CuzViR3Gi3eYH3VuNGVy0qhDONR6d4jj+/pvEEsAIuwVMl4VTwuAR/TvvEXntn//WsHR3QoanUu0FAqbiFHlKYduJbYzQ80Ri6vzaoNiVEy/NDPbnl9c5R2hGVq9CLDgo356K5Cn9jqFb/UdhFJYOLycMj34EG9RrTNB5alvJLmVAPdKPEsNndrRhugmJJkGICk/4dRQUxkZf9RzdVEL9Ox8deT4HdwT8xi/NE2nOcCXH3sZ5zK6a2tTPUMpJPP45H2PZ/xWSUdfs4AneAoPfwt4AEW7YlkOdiqRTOZs9zXA2cdONDHIYgE7Ju38ve9Uz3AV7LYmPGv+VCWYnW5v+3ug5VbNQX18MUqSv4fnIdm5HmoUuS2qZEDX6Czi0gHnWgVAQZ0P1P9w+CeisC927T6adbKDPwl5OdyI6+/zdO8RDPBTVu6FBZM8ddLeETpEqLfuD8Bg5XjDlua3MxRbAfchpahnBxwZQpr6BDBfUJT0r82Lc2pjQQ5L4TVn9vwAlXolv/f221/jizFtSSMJKwlF/KF3f2EsTmPY=
